FROM golang:1.9-alpine3.7

RUN apk update && apk upgrade && apk add --no-cache bash git

RUN go get github.com/Todai88/faceIt/microservice/api

ENV SOURCES /go/src/github.com/Todai88/faceIt/microservice/api/
ENV PORT 5050
COPY . ${SOURCES}

RUN cd ${SOURCES}microservice/ && CGO_ENABLED=0 go build

WORKDIR ${SOURCES}microservice/
EXPOSE ${PORT}

CMD ${SOURCES}microservice/microservice